# Copyright (c) CloudBees, Inc.

name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "📚 Documentation"
    label: "documentation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## CloudBees CI

  Application: [![Application](https://img.shields.io/badge/x.xx.x.x-informational?style=flat-square)](https://docs.cloudbees.com/docs/release-notes/latest/cloudbees-ci/modern-cloud-platforms/x.xx.x.x)
  Helm Chart: [![Application](https://img.shields.io/badge/x.xx.x.x-informational?style=flat-square)](https://artifacthub.io/packages/helm/cloudbees/cloudbees-core/xxxxxxxxxxxxxx)

  ## Changes

  $CHANGES
