# Copyright (c) CloudBees, Inc.

fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
      args: ['--markdown-linebreak-ext=md']
    - id: end-of-file-fixer
    - id: check-added-large-files
      args: [--maxkb=1024]
    - id: detect-private-key
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-symlinks
    - id: destroyed-symlinks
    - id: check-yaml
      args: [--allow-multiple-documents]
      exclude: "templates/.*"
    - id: check-vcs-permalinks

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.92.0
  hooks:
    - id: terraform_fmt
      name: Format Terraform Configuration
    - id: terraform_validate
      name: Validate Terraform Configuration
      args:
        - --hook-config=--retry-once-with-cleanup=true
    - id: terraform_tflint
      args:
        #- '--args=--only=terraform_deprecated_interpolation'
        - '--args=--only=terraform_deprecated_index'
        - '--args=--only=terraform_unused_declarations'
        - '--args=--only=terraform_comment_syntax'
        - '--args=--only=terraform_documented_outputs'
        - '--args=--only=terraform_documented_variables'
        - '--args=--only=terraform_typed_variables'
        - '--args=--only=terraform_module_pinned_source'
        - '--args=--only=terraform_naming_convention'
        - '--args=--only=terraform_required_version'
        - '--args=--only=terraform_required_providers'
        - '--args=--only=terraform_standard_module_structure'
        - '--args=--only=terraform_workspace_remote'
    - id: terraform_docs
      name: Generate Terraform README files
      args:
        - "--args=--config=.terraform-docs.yml"
        - "--args=--lockfile=false"
        - --hook-config=--create-file-if-not-exist=true
