# Copyright (c) CloudBees, Inc.

# https://artifacthub.io/packages/helm/aws/aws-for-fluent-bit
# https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/values.yaml

tolerations:
- effect: "NoSchedule"
  key: "${cbciAppsTolerationKey}"
  operator: "Equal"
  value: "${cbciAppsTolerationValue}"
- effect: "NoSchedule"
  key: "dedicated"
  operator: "Equal"
  value: "linux-builds"
# Note: It is not compatible with Windows nodes by default.
# - effect: "NoSchedule"
#   key: "dedicated"
#   operator: "Equal"
#   value: "windows-builds-2022"

cloudWatchLogs:
  enabled: true
  region: "${region}"
  logRetentionDays : ${log_retention_days}

s3:
  enabled: true
  region: "${region}"
  bucket: "${bucketName}"
  s3KeyFormat: /fluentbit/$TAG/%Y-%m-%d/%H-%M-%S

additionalOutputs: |
  [OUTPUT]
      name                   loki
      host                   loki.observability.svc.cluster.local
      port                   3100
      match                  *
      labels                 job=fluentbit
      auto_kubernetes_labels on
