# Copyright (c) CloudBees, Inc.

#https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/README.md#configuration

#Planned Update: checks every Saturday at 23H / 11PM
scheduler_cron_expression: "0 0 23 * * Sat *"

#TODO: Add toleration for bottle rockets nodes
placement:
  agent:
    # The agent is a daemonset, so the only controls that apply to it are tolerations.
    tolerations:
    - key: dedicated
      operator: Equal
      value: build-linux #TODO: Use Templates
      effect: NoSchedule
    - key: dedicated
      operator: Equal
      value: cb-apps #TODO: Use Templates
      effect: NoSchedule
    #TODO: Add selector for bottle rockets nodes

    controller:
      nodeSelector: 
        kubernetes.io/os: linux

    apiserver:
      nodeSelector: 
        kubernetes.io/os: linux