# Copyright (c) CloudBees, Inc.

#https://artifacthub.io/packages/helm/cloudbees/cloudbees-core/
#https://docs.cloudbees.com/docs/cloudbees-ci/latest/eks-install-guide/installing-eks-using-helm

OperationsCenter:
  Ingress:
    Annotations:
      alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true
  NodeSelector:
    ${cbciAppsSelector}
  Tolerations:
    - key: ${cbciAppsTolerationKey}
      operator: Equal
      value: ${cbciAppsTolerationValue}
      effect: NoSchedule
  CasC:
    Enabled: true
    Retriever:
      Enabled: true
      scmRepo: https://github.com/cloudbees/terraform-aws-cloudbees-ci-eks-addon.git
      scmBranch: main
      scmBundlePath: blueprints/02-at-scale/casc/oc
      scmPollingInterval: PT20M
Persistence:
  StorageClass: efs
Hibernation:
  Enabled: true
  NodeSelector:
    ${cbciAppsSelector}
  Tolerations:
    - key: ${cbciAppsTolerationKey}
      operator: Equal
      value: ${cbciAppsTolerationValue}
      effect: NoSchedule
Agents:
  SeparateNamespace:
    Enabled: true
    Create: true
    Name: ${cbciAgentsNamespace}
