{
 "title": "Updated CloudBees - Prometheus Plugin",
 "tags": [
  "jenkins",
  "cloudbees",
  "ci"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "query_result(up{container=\"jenkins\"})"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "query_result(up{container=\"jenkins\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "CBCI Pod - Readiness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jenkins Health Score",
   "type": "gauge",
   "description": "Average Jenkins Health Score over the time (%) in the defined interval.\n\nScore based on healthy disk space, failed plugins, healthy temporary space, and thread deadlocks.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(jenkins_health_check_score{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Instance Uptime (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(up{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Plugins Failed",
   "type": "stat",
   "description": "Sum of Number of Failed Plugins. A value other than 0 is typically indicative of a potential issue within the Jenkins installation that will either be solved by explicitly disabling the plugin(s) or by resolving the plugin dependency issues.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_plugins_failed{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Number of JVM Deadlocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vm_deadlock_count{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg(process_max_fds{pod=~\"$pod\"}) ",
     "legendFormat": "Max Open Files"
    },
    {
     "expr": "avg(process_open_fds{pod=~\"$pod\"}) ",
     "legendFormat": "Open files"
    }
   ]
  },
  { "title": "CBCI Pod - JVM status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "JVM CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(vm_cpu_load{pod=~\"$pod\"})",
     "legendFormat": "{{pod}} JVM CPU Load"
    }
   ]
  },
  {
   "title": "Memory  Heap Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n\n\n(avg(vm_memory_total_used {pod=\"$pod\"}) / avg(vm_memory_heap_max {pod=\"$pod\"})) * 100"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(vm_memory_total_used{pod=\"$pod\"})",
     "legendFormat": "JVM Used Memory"
    },
    {
     "expr": "avg(vm_memory_total_committed{pod=\"$pod\"})",
     "legendFormat": "JVM Comitted Memory"
    },
    {
     "expr": "avg(vm_memory_heap_max{pod=\"$pod\"})",
     "legendFormat": "JVM Heap Memory Limit"
    }
   ]
  },
  { "title": "CBCI Pod - Plugins Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Plugins Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_plugins_active{pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Plugins Update Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_plugins_withUpdate{pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Plugins inactive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_plugins_inactive{pod=\"$pod\"})"
    }
   ]
  },
  { "title": "CBCI Pod - HTTP Request Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "HTTP Request Duration (99%)",
   "type": "timeseries",
   "description": "The 99% percentile of HTTP Requests handled by Jenkins masters.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "avg(http_requests{pod=~\"$pod\",quantile=\"0.99\"})"
    }
   ]
  },
  {
   "title": "Good HTTP Request Ratio",
   "type": "timeseries",
   "description": "The ratio of ok (200) request out of all requests.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "avg(http_responseCodes_ok_total{pod=~\"$pod\"})/ \navg(http_requests_count{pod=~\"$pod\"}) "
    }
   ]
  },
  {
   "title": "HTTP Server Errors",
   "type": "timeseries",
   "description": "Http Server Errors (500)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "avg(rate(http_responseCodes_serverError_total{pod=~\"$pod\"}[1m]))"
    }
   ]
  },
  { "title": "CBCI Service - Builds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Current Number of Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_job_count_value{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Build Completion Status",
   "type": "piechart",
   "description": "Comparison of build completion status' within specified time interval.\n\nSuccess: The Build has no errors, and completed.\n\nFailure: The Build had a fatal error, and did not complete.\n\nAborted: The Build was interrupted before it reaches its expected end. For example, the user has stopped it manually or there was a time-out.\n\nUnstable: The Build had some errors but they were not fatal. The build completed.\n\nNot Built: The Build was scheduled but cancelled and not started. This could be due to manual intervention or concurrent builds are not allowed.",
   "gridPos": { "h": 11, "w": 16, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(service) (increase(jenkins_runs_unstable_total{service=~\"$service\"}[$__range]))",
     "legendFormat": "Unstable"
    },
    {
     "expr": "sum by(service) (increase(jenkins_runs_aborted_total{service=~\"$service\"}[$__range]))",
     "legendFormat": "Aborted"
    },
    {
     "expr": "sum by(service) (increase(jenkins_runs_success_total{service=~\"$service\"}[$__range]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by(service) (increase(jenkins_runs_failure_total{service=~\"$service\"}[$__range]))",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum by(service) (increase(jenkins_runs_not_built_total{service=~\"$service\"}[$__range]))",
     "legendFormat": "Not Built"
    }
   ]
  },
  {
   "title": "Current queue size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_queue_size_value{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Processing speed (per min)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(jenkins_job_building_duration_count{service=~\"$service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Queued rate (per min)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(jenkins_job_queuing_duration_count{service=~\"$service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Average Queue Time",
   "type": "timeseries",
   "description": "Average time spent in the queue.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(jenkins_job_queuing_duration{service=~\"$service\"})",
     "legendFormat": "Queuing"
    },
    {
     "expr": "avg(jenkins_job_waiting_duration{service=~\"$service\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "avg(jenkins_job_blocked_duration{service=~\"$service\"})",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Average Build Time",
   "type": "timeseries",
   "description": "Average time spent in the building.\n\nBuild: Total time spent executing the build.\n\nTotal: Time spent in the queue as well as completing the build.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(jenkins_job_total_duration{service=~\"$service\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(jenkins_job_building_duration{service=~\"$service\"})",
     "legendFormat": "Building"
    }
   ]
  },
  {
   "title": "Build Rate (per 1h)",
   "type": "timeseries",
   "description": "Number of Builds per hour",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(jenkins_runs_total_total{}[$__range])) * 3600",
     "legendFormat": "{{controller_name}}"
    }
   ]
  },
  {
   "title": "Building Rate (Jobs/1h)",
   "type": "bargauge",
   "description": "Rate (5m range)  at which jobs are built and the time they spend building per 1 hour (Meter).",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count{service=~\"$service\"}[5m])*3600",
     "legendFormat": "{{controller_name}}"
    }
   ]
  },
  {
   "title": "CJOC Shared Agent Nodes",
   "type": "timeseries",
   "description": "Represents shared agent nodes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "operations_center_shared_cloud_nodes_available_value{service=\"$service\"}",
     "legendFormat": "Available Nodes"
    },
    {
     "expr": "operations_center_shared_cloud_nodes_leased_value{service=\"$service\"}",
     "legendFormat": "Leased Nodes"
    }
   ]
  },
  {
   "title": "Executor Efficiency",
   "type": "timeseries",
   "description": "Graph of available executors vs in use",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "jenkins_executor_in_use_value{service=\"$service\"}",
     "legendFormat": "Executors In Use"
    },
    {
     "expr": "jenkins_executor_count_value{service=\"$service\"}",
     "legendFormat": "Total Executors"
    }
   ]
  }
 ]
}