# Copyright (c) CloudBees, Inc.

# https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/values.yaml

provisionDataStore:
  cassandra: false
allInOne:
  enabled: true
  nodeSelector:
      kubernetes.io/os: linux
storage:
  type: memory
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
