# Copyright (c) CloudBees, Inc.

# https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/values.yaml

nodeSelector:
  kubernetes.io/os: linux

provisionDataStore:
  cassandra: false
allInOne:
  enabled: true
storage:
  type: memory
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
