# Copyright (c) CloudBees, Inc.

#https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-collector
#https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml

nodeSelector:
  kubernetes.io/os: linux

image:
  repository: "otel/opentelemetry-collector-contrib"

mode: "deployment"
presets:
  kubernetesAttributes:
    enabled: true
service:
    type: ClusterIP
ports:
  metrics:
    enabled: true
  prometheus:
    enabled: true
    containerPort: 8889
    servicePort: 8889
    protocol: TCP
config:
  receivers:
    otlp/jenkins:
      protocols:
        grpc:
          endpoint: '${env:MY_POD_IP}:4317'
  exporters:
    otlphttp/loki:
      endpoint: 'http://loki-gateway/otlp'
    otlp/jaeger:
      endpoint: 'jaeger-collector:4317'
      tls:
        insecure: true
    prometheus:
      endpoint: '${env:MY_POD_IP}:8889'
      resource_to_telemetry_conversion:
        enabled: true
  service:
    pipelines:
      logs:
        receivers:
          - otlp/jenkins
        processors:
          - batch
        exporters:
          - otlphttp/loki
          - debug
      traces:
        receivers:
          - otlp/jenkins
        processors:
          - batch
        exporters:
          - otlp/jaeger
          - debug
      metrics:
        receivers:
          - otlp/jenkins
        processors:
          - batch
        exporters:
          - prometheus
          - debug
