jenkins:
  securityRealm:
    ldap:
      configurations:
      - managerDN: ${ldap_ManagerDN}
        managerPasswordSecret: ${ldap_ManagerPasswordSecret}
        rootDN: ${ldap_RootDN}
        server: ${ldap_Server}
        userSearch: ${ldap_UserSearch}
  authorizationStrategy: "cloudBeesRoleBasedAccessControl"
  remotingSecurity:
    enabled: true
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "GH-User-token"
          id: "GH-User-token"
          password: ${secGithubUser}
          scope: GLOBAL
          username: ${secGithubToken}
          usernameSecret: true
      - string:
          description: "GH-ST-token"
          id: "GH-ST-token"
          scope: GLOBAL
          secret: ${secGithubToken}
