jenkins:
  securityRealm:
    ldap:
      configurations:
      - managerDN: ${ldapManagerDN}
        managerPasswordSecret: ${sec_globalPassword}
        rootDN: ${ldapRootDN}
        server: ${ldapServer}
        userSearch: ${ldapUserSearch}
  authorizationStrategy: "cloudBeesRoleBasedAccessControl"
  remotingSecurity:
    enabled: true
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "GH-User-token"
          id: "GH-User-token"
          password: ${sec_githubUser}
          scope: GLOBAL
          username: ${sec_githubToken}
          usernameSecret: true
      - string:
          description: "GH-ST-token"
          id: "GH-ST-token"
          scope: GLOBAL
          secret: ${sec_githubToken}
