# Copyright (c) CloudBees, Inc.

apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ci

on:
  # Enable once Issue #83 is solved
  # pull_request:
  #   branches:
  #     - 'main'
  workflow_dispatch:

env:
  AWS_REGION: "us-east-1"
  BUCKET_NAME_TF_STATE: "cbci-eks-addon-tf-state-v2"
  AWS_ROLE_TO_ASSUME: "infra-admin-ci"
  TF_AUTO_VARS_FILE: |
    tags = {
      "cb-owner" : "professional-services"
      "cb-user" : "cb-platform"
      "cb-purpose" : "ci"
    }
    trial_license = {
      first_name  = "CloudBees.io"
      last_name  = "Platform"
      email = "ci.user@cloudbees.io"
      company = "CloudBees Inc."
    }
    suffix = "ci-v11"
    ci = true

jobs:
  init:
    steps:

    - name: Configure AWS Credentials
      uses: cloudbees-io/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_TF_CBCI_EKS_AccessKeyID }}
        aws-secret-access-key: ${{ secrets.AWS_TF_CBCI_EKS_SecretAccessKey }}
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        role-external-id: cloudbees
        role-duration-seconds: "3600"

    #TODO: Add tags for the bucket
    - name: Create Terraform Backend Bucket if not exists
      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
      shell: bash
      run: |
        set -x
        aws s3api create-bucket \
          --bucket ${{ env.BUCKET_NAME_TF_STATE }} \
          --region ${{ env.AWS_REGION }} || echo "Bucket ${{ env.BUCKET_NAME_TF_STATE }} already exists"
        aws kms delete-alias --alias-name alias/eks/cbci-bp01-ci-v11-eks --region us-west-2

  bp01:
    env:
      ROOT: 01-getting-started
      TF_VAR_hosted_zone: bp01.aws.ps.beescloud.com
      # Add the stages to execute in the pipeline: deploy,validate,destroy,wipeout
      STAGES: ""
    needs:
      - init
    steps:

    - name: Configure AWS Credentials
      uses: cloudbees-io/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_TF_CBCI_EKS_AccessKeyID }}
        aws-secret-access-key: ${{ secrets.AWS_TF_CBCI_EKS_SecretAccessKey }}
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        role-external-id: cloudbees
        role-duration-seconds: "3600"

    - name: Checkout code
      uses: cloudbees-io/checkout@v1

    - name: 01-getting-started - Set
      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
      shell: bash
      run : |
        cat <<EOT >> blueprints/${{ env.ROOT }}/.auto.tfvars
        ${{ env.TF_AUTO_VARS_FILE }}
        EOT
        cat <<EOT >> blueprints/${{ env.ROOT }}/backend.tf
        terraform {
          backend "s3" {
            bucket = "${{ env.BUCKET_NAME_TF_STATE }}"
            key    = "${{ env.ROOT }}/ci.terraform.tfstate"
            region = "${{ env.AWS_REGION }}"
          }
        }
        EOT

    - name: 01-getting-started - Deploy
      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
      if: contains(env.STAGES, 'deploy')
      shell: bash
      run : |
        CI=true make deploy
        aws s3api put-object \
            --bucket ${{ env.BUCKET_NAME_TF_STATE }} \
            --region ${{ env.AWS_REGION }} \
            --key ${{ env.ROOT }}/${{ env.ROOT }}.kubeconfig.yaml \
            --body $(cd blueprints/${{ env.ROOT }} && terraform output --raw kubeconfig_file)

    - name: 01-getting-started - Validate
      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
      if: contains(env.STAGES, 'validate')
      shell: bash
      run : |
        CI=true make validate

    - name: 01-getting-started - Destroy
      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
      if: contains(env.STAGES, 'destroy')
      shell: bash
      run : |
        CI=true make destroy

    - name: 01-getting-started - Wipeout Failed Deployment
      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
      if: contains(env.STAGES, 'wipeout')
      shell: bash
      run : |
        terraform -chdir=blueprints/${{ env.ROOT }} init -reconfigure && CI=true make destroy

  bp02:
    env:
      ROOT: 02-at-scale
      TF_VAR_hosted_zone: bp02.aws.ps.beescloud.com
      # Add the stages to execute in the pipeline: deploy,validate,destroy,wipeout
      STAGES: ""
    needs:
      - init
    steps:

    - name: Configure AWS Credentials
      uses: cloudbees-io/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_TF_CBCI_EKS_AccessKeyID }}
        aws-secret-access-key: ${{ secrets.AWS_TF_CBCI_EKS_SecretAccessKey }}
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        role-external-id: cloudbees
        role-duration-seconds: "3600"

    - name: Checkout code
      uses: cloudbees-io/checkout@v1

    - name: 02-at-scale - Set
      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
      shell: bash
      run : |
        cat <<EOT >> blueprints/${{ env.ROOT }}/.auto.tfvars
        ${{ env.TF_AUTO_VARS_FILE }}
        dh_reg_secret_auth = {
          username = "foo"
          password = "d0ckerPass12"
          email = "example@gmail.com"
        }
        EOT
        cat <<EOT >> blueprints/${{ env.ROOT }}/backend.tf
        terraform {
          backend "s3" {
            bucket = "${{ env.BUCKET_NAME_TF_STATE }}"
            key    = "${{ env.ROOT }}/ci.terraform.tfstate"
            region = "${{ env.AWS_REGION }}"
          }
        }
        EOT

    - name: 02-at-scale - Deploy
      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
      if: contains(env.STAGES, 'deploy')
      shell: bash
      run : |
        CI=true make deploy
        set -x
        aws s3api put-object \
            --bucket ${{ env.BUCKET_NAME_TF_STATE }} \
            --region ${{ env.AWS_REGION }} \
            --key ${{ env.ROOT }}/${{ env.ROOT }}.kubeconfig.yaml \
            --body $(cd blueprints/${{ env.ROOT }} && terraform output --raw kubeconfig_file)

    - name: 02-at-scale - Validate
      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
      if: contains(env.STAGES, 'validate')
      shell: bash
      run : |
        CI=true make validate

    - name: 02-at-scale - Destroy
      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
      if: contains(env.STAGES, 'destroy')
      shell: bash
      run : |
        CI=true make destroy
    
    - name: 02-at-scale - Wipeout Failed Deployment
      uses: docker://public.ecr.aws/r1n1q0e5/cloudbees-labs/tf-aws-cb-ci-eks-addon-agent:latest
      if: contains(env.STAGES, 'wipeout')
      shell: bash
      run : |
        terraform -chdir=blueprints/${{ env.ROOT }} init -reconfigure && CI=true make destroy
