# Copyright (c) CloudBees, Inc.
---

name: "Documentation: MD Links Checker"

on:
  pull_request:

jobs:
  check-links:
    name: MD_Check_Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/markdown.links.config.json'
