apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
spec:
  containers:
    - name: shell
      image: mcr.microsoft.com/powershell:preview-windowsservercore-1809
      resources:
        limits:
          memory: "1Gi"
        requests:
          memory: "500Mi"
          cpu: "250m"
      command:
        - powershell
      args:
        - Start-Sleep
        - "999999"
  nodeSelector:
    kubernetes.io/os: windows
    role: windows-builds
    type: "windows_2019"
  tolerations:
    - effect: "NoSchedule"
      key: "dedicated"
      operator: "Equal"
      value: "windows-builds-2019"
