apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-a
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateful
  template:
    metadata:
      labels:
        app: stateful
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "linux-builds"
        effect: "NoSchedule"
      terminationGracePeriodSeconds: 0
      nodeSelector:
        role: linux-builds
      containers:
      - name: stateful
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo Writing content every three minutes! Printing a random number: $(( $RANDOM % 1000 + 1 ))>> /data/out.txt; sleep 180; done"]
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
        resources:
          requests:
            cpu: 1
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ebs-claim
